import Layout from "../components/layout";
import Head from "next/head";

export default function Projects() {
	return (
		<Layout>
			<Head>
				<title>Next 연습!!</title>
				<meta name="description" content="Generated by create next app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			프로젝트
		</Layout>
	)
}
